# Generated by Django 2.1.4 on 2019-05-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapAttractions',
            fields=[
                ('attractionsId', models.AutoField(primary_key=True, serialize=False)),
                ('attractionsName', models.CharField(max_length=30)),
                ('attractionsToldescribe', models.CharField(max_length=300)),
                ('attractionsAddress', models.CharField(max_length=30)),
                ('attractionsOpentime', models.CharField(max_length=30)),
                ('attractionsPx', models.FloatField(max_length=30)),
                ('attractionsPy', models.FloatField(max_length=30)),
                ('attractionsParkinfo', models.CharField(max_length=30)),
                ('attractionsTel', models.CharField(max_length=15)),
            ],
        ),
    ]
