# Generated by Django 2.1.4 on 2019-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapattractions',
            name='attractionsId',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
