# Generated by Django 2.1.4 on 2019-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('memberId', models.AutoField(primary_key=True, serialize=False)),
                ('memberAccount', models.CharField(max_length=70)),
                ('memberEmail', models.EmailField(max_length=70)),
                ('memberPassword', models.CharField(max_length=30)),
                ('memberName', models.CharField(max_length=30)),
                ('dailyConsum', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
