# Generated by Django 2.1.4 on 2019-05-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='memberAccount',
        ),
    ]
