# Generated by Django 2.1.4 on 2019-05-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_memberaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='laskWeek',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='lastWeekConsume',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nowDay',
            field=models.DateField(null=True),
        ),
    ]
