# Generated by Django 2.1.4 on 2019-05-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190513_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dailyConsum',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastWeekConsume',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
