# Generated by Django 2.1.4 on 2019-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190513_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dailyConsum',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastWeekConsume',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
