# Generated by Django 2.1.4 on 2019-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carbon',
            fields=[
                ('carbonId', models.AutoField(primary_key=True, serialize=False)),
                ('carbonClass', models.CharField(max_length=10)),
                ('carbonName', models.CharField(max_length=20)),
                ('carbonCoporation', models.CharField(max_length=20)),
                ('carbonFootprint', models.CharField(max_length=10)),
                ('carbonUnit', models.CharField(max_length=15)),
            ],
        ),
    ]
